/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export function defineContractComponents(world: World) {
  return {
	  ActionPoint: (() => {
	    return defineComponent(
	      world,
	      { id: RecsType.Number, game_id: RecsType.BigInt, value: RecsType.Number },
	      {
	        metadata: {
	          name: "ActionPoint",
	          types: ["u8","felt252","u8"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  Alive: (() => {
	    return defineComponent(
	      world,
	      { id: RecsType.Number, game_id: RecsType.BigInt, value: RecsType.Boolean },
	      {
	        metadata: {
	          name: "Alive",
	          types: ["u8","felt252","bool"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  ClaimInterval: (() => {
	    return defineComponent(
	      world,
	      { player: RecsType.BigInt, value: RecsType.Number },
	      {
	        metadata: {
	          name: "ClaimInterval",
	          types: ["contractaddress","u64"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  GameData: (() => {
	    return defineComponent(
	      world,
	      { game: RecsType.BigInt, board_width: RecsType.Number, board_height: RecsType.Number, claim_interval: RecsType.Number, number_of_players: RecsType.Number, available_ids: RecsType.BigInt },
	      {
	        metadata: {
	          name: "GameData",
	          types: ["felt252","u32","u32","u64","u8","u256"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  GameSession: (() => {
	    return defineComponent(
	      world,
	      { id: RecsType.BigInt, isLive: RecsType.Boolean, startTime: RecsType.BigInt, gameId: RecsType.BigInt, live_players: RecsType.Number, players: RecsType.Number, isWon: RecsType.Boolean },
	      {
	        metadata: {
	          name: "GameSession",
	          types: ["felt252","bool","felt252","felt252","u8","u8","bool"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  Health: (() => {
	    return defineComponent(
	      world,
	      { id: RecsType.Number, game_id: RecsType.BigInt, value: RecsType.Number },
	      {
	        metadata: {
	          name: "Health",
	          types: ["u8","felt252","u8"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  InGame: (() => {
	    return defineComponent(
	      world,
	      { id: RecsType.Number, game_id: RecsType.BigInt, player: RecsType.BigInt },
	      {
	        metadata: {
	          name: "InGame",
	          types: ["u8","felt252","contractaddress"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  LastActionPointClaim: (() => {
	    return defineComponent(
	      world,
	      { id: RecsType.Number, game_id: RecsType.BigInt, value: RecsType.Number },
	      {
	        metadata: {
	          name: "LastActionPointClaim",
	          types: ["u8","felt252","u64"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  LastVotingPointClaim: (() => {
	    return defineComponent(
	      world,
	      { id: RecsType.Number, game_id: RecsType.BigInt, value: RecsType.Number },
	      {
	        metadata: {
	          name: "LastVotingPointClaim",
	          types: ["u8","felt252","u64"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  Player: (() => {
	    return defineComponent(
	      world,
	      { player: RecsType.BigInt, gameId: RecsType.BigInt },
	      {
	        metadata: {
	          name: "Player",
	          types: ["contractaddress","felt252"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  PlayerAddress: (() => {
	    return defineComponent(
	      world,
	      { id: RecsType.Number, player: RecsType.BigInt },
	      {
	        metadata: {
	          name: "PlayerAddress",
	          types: ["u8","contractaddress"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  PlayerAtPosition: (() => {
	    return defineComponent(
	      world,
	      { x: RecsType.Number, y: RecsType.Number, game_id: RecsType.BigInt, id: RecsType.Number },
	      {
	        metadata: {
	          name: "PlayerAtPosition",
	          types: ["u8","u8","felt252","u8"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  PlayerId: (() => {
	    return defineComponent(
	      world,
	      { player: RecsType.BigInt, id: RecsType.Number },
	      {
	        metadata: {
	          name: "PlayerId",
	          types: ["contractaddress","u8"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  Position: (() => {
	    return defineComponent(
	      world,
	      { id: RecsType.Number, game_id: RecsType.BigInt, x: RecsType.Number, y: RecsType.Number },
	      {
	        metadata: {
	          name: "Position",
	          types: ["u8","felt252","u8","u8"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  Range: (() => {
	    return defineComponent(
	      world,
	      { id: RecsType.Number, game_id: RecsType.BigInt, value: RecsType.Number },
	      {
	        metadata: {
	          name: "Range",
	          types: ["u8","felt252","u8"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  Square: (() => {
	    return defineComponent(
	      world,
	      { x: RecsType.Number, y: RecsType.Number, game_id: RecsType.BigInt, piece: RecsType.Number },
	      {
	        metadata: {
	          name: "Square",
	          types: ["u8","u8","felt252","enum"],
	          customTypes: ["PieceType"],
	        },
	      }
	    );
	  })(),
	  Username: (() => {
	    return defineComponent(
	      world,
	      { id: RecsType.Number, game_id: RecsType.BigInt, value: RecsType.BigInt },
	      {
	        metadata: {
	          name: "Username",
	          types: ["u8","felt252","felt252"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  VotingPoint: (() => {
	    return defineComponent(
	      world,
	      { id: RecsType.Number, game_id: RecsType.BigInt, value: RecsType.Number },
	      {
	        metadata: {
	          name: "VotingPoint",
	          types: ["u8","felt252","u8"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  PlayerSpawned: (() => {
		return defineComponent(
		  world,
		  {
			timestamp: RecsType.BigInt,
			at: { x: RecsType.Number, y: RecsType.Number },
			gameId: RecsType.BigInt,
			player: RecsType.String,
		  },
		  {
			metadata: {
			  name: "PlayerSpawned",
			  types: ["felt252", "u8", "u8", "felt252", "felt252"],
			  customTypes: ["Coordinate"],
			},
		  }
		);
	  })(),
	  GameStarted: (() => {
		return defineComponent(
		  world,
		  { 
			startTime: RecsType.BigInt, 
			gameId: RecsType.BigInt 
		  },
		  {
			metadata: {
			  name: "GameStarted",
			  types: ["felt252", "felt252"],
			  customTypes: [],
			},
		  }
		);
	  })(),
	  PlayerMoved: (() => {
		return defineComponent(
		  world,
		  { timestamp: RecsType.BigInt,
			from: { x: RecsType.Number, y: RecsType.Number },
			to: { x: RecsType.Number, y: RecsType.Number },
			gameId: RecsType.BigInt,
			player: RecsType.String,
		  },
		  {
			metadata: {
			  name: "PlayerMoved",
			  types: ["felt252", "u8", "u8", "u8", "u8", "felt252", "felt252"],
			  customTypes: ["Coordinate"],
			},
		  }
		);
	  })(),
	  RangeIncreased: (() => {
		return defineComponent(
		  world,
		  { 
			timestamp: RecsType.BigInt, 
			gameId: RecsType.BigInt,
			player: RecsType.String, 
			newRange: RecsType.Number,
		  },
		  {
			metadata: {
			  name: "RangeIncreased",
			  types: ["felt252", "felt252", "felt252", "u8"],
			  customTypes: [],
			},
		  }
		);
	  })(),
	  ActionPointClaimed: (() => {
		return defineComponent(
		  world,
		  { 
			timestamp: RecsType.Number, 
			gameId: RecsType.BigInt,
			player: RecsType.String, 
		  },
		  {
			metadata: {
			  name: "ActionPointClaimed",
			  types: ["u64", "felt252", "felt252"],
			  customTypes: [],
			},
		  }
		);
	  })(),
	  VotingPointClaimed: (() => {
		return defineComponent(
		  world,
		  { 
			timestamp: RecsType.Number, 
			gameId: RecsType.BigInt,
			player: RecsType.String, 
		  },
		  {
			metadata: {
			  name: "VotingPointClaimed",
			  types: ["u64", "felt252", "felt252"],
			  customTypes: [],
			},
		  }
		);
	  })(),
	  ActionPointSent: (() => {
		return defineComponent(
		  world,
		  { 
			timestamp: RecsType.BigInt, 
			gameId: RecsType.BigInt,
			sender: RecsType.String, 
			receiver: RecsType.String,
		  },
		  {
			metadata: {
			  name: "ActionPointSent",
			  types: ["felt252", "felt252", "felt252", "felt252"],
			  customTypes: [],
			},
		  }
		);
	  })(),
	  Voted: (() => {
		return defineComponent(
		  world,
		  { 
			timestamp: RecsType.BigInt, 
			gameId: RecsType.BigInt,
			voter: RecsType.String, 
			receiver: RecsType.String,
		  },
		  {
			metadata: {
			  name: "Voted",
			  types: ["felt252", "felt252", "felt252", "felt252"],
			  customTypes: [],
			},
		  }
		);
	  })(),
	  PlayerKilled: (() => {
		return defineComponent(
		  world,
		  { 
			timestamp: RecsType.Number, 
			gameId: RecsType.BigInt,
			killer: RecsType.String, 
			killed: RecsType.String,
		  },
		  {
			metadata: {
			  name: "Voted",
			  types: ["u64", "felt252", "felt252", "felt252"],
			  customTypes: [],
			},
		  }
		);
	  })(),
	  AttackExecuted: (() => {
		return defineComponent(
		  world,
		  { 
			timestamp: RecsType.Number, 
			gameId: RecsType.BigInt,
			attacker: RecsType.String, 
			target: RecsType.String,
		  },
		  {
			metadata: {
			  name: "Voted",
			  types: ["u64", "felt252", "felt252", "felt252"],
			  customTypes: [],
			},
		  }
		);
	  })(),
	  GameEnded: (() => {
		return defineComponent(
		  world,
		  { 
			timestamp: RecsType.Number, 
			gameId: RecsType.BigInt, 
			winning_player: RecsType.String,
		  },
		  {
			metadata: {
			  name: "GameEnded",
			  types: ["u64", "felt252", "felt252"],
			  customTypes: [],
			},
		  }
		);
	  })(),
  };
}
